"""Scale-out: register a new automation as a standing concern + skill scaffold.

This is how the CEO grows the system. `ernest new-automation` adds a concern
(so the watch engine picks it up immediately) and scaffolds a SKILL.md the
Claude layer can read and refine. No behavior is changed silently: the concern
is plain text the CEO can inspect.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from .concerns import Concern, register
from .config import Config

_KNOWN_PLAYBOOKS = {"account-followup-recovery", "inbox-prospect-followup"}

_SKILL_TEMPLATE = """---
name: {id}
description: {description}
---

# {title}

Generated by `ernest new-automation`. Refine this freely.

## Trigger
Standing concern `{id}` (playbook `{playbook}`) in `memory/standing-concerns.md`.
The watch engine evaluates it every run.

## What Ernest does
1. Read matching threads/contacts (VPS brain -> local MCP -> `data/` exports).
2. Apply the `{playbook}` detection rules.
3. Write a remind-only card to `00-Watch/`.
4. On "draft these", produce draft-only outreach in `00-Drafts/` for approval.

## Guardrails
- Remind-only by default. Never sends without CEO approval (enforced by the gate).
- Outputs are labeled with their source.

## Parameters
{params}
"""


def scaffold(cfg: Config, concern_id: str, playbook: str, description: str,
             staleness: Optional[str] = None, intent: Optional[str] = None,
             window: Optional[str] = None) -> dict:
    if playbook not in _KNOWN_PLAYBOOKS:
        raise ValueError(
            f"Unknown playbook '{playbook}'. Known: {', '.join(sorted(_KNOWN_PLAYBOOKS))}"
        )
    params: dict[str, str] = {}
    if staleness:
        params["staleness"] = staleness
    if intent:
        params["intent"] = intent
    if window:
        params["window"] = window
    if playbook == "account-followup-recovery" and "staleness" not in params:
        params["staleness"] = "7d"
    if playbook == "inbox-prospect-followup" and "window" not in params:
        params["window"] = "90d"

    added = register(cfg, Concern(id=concern_id, playbook=playbook, enabled=True, params=params))

    skill_dir = cfg.skills_dir / concern_id
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    param_block = "\n".join(f"- {k}: {v}" for k, v in params.items()) or "- (none)"
    skill_path.write_text(
        _SKILL_TEMPLATE.format(
            id=concern_id,
            description=description or f"Automation for {concern_id}",
            title=concern_id.replace("-", " ").title(),
            playbook=playbook,
            params=param_block,
        ),
        encoding="utf-8",
    )
    return {"concern_added": added, "skill_path": skill_path, "params": params}
