"""Scale-out: register a new automation as a standing concern + skill scaffold.

This is how the CEO grows the system. `ernest new-automation` adds a concern
(so the watch engine picks it up immediately) and scaffolds a SKILL.md the
Claude layer can read and refine. No behavior is changed silently: the concern
is plain text the CEO can inspect.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from .concerns import Concern, register
from .config import Config

_KNOWN_PLAYBOOKS = {
    "account-followup-recovery", "inbox-prospect-followup", "add-collaborator",
    "candidate-followup", "list-sync", "sourcing-pipeline", "task-tracker",
}

_SKILL_TEMPLATE = """---
name: {id}
description: {description}
version: 0.1.0
---

# {title}

Generated by `ernest new-automation`. Refine this freely — the section shape
below is the house standard (deep skills fill every section; delete none).

## When to use
Standing concern `{id}` (playbook `{playbook}`) — evaluated on every watch run.
Also on demand when the CEO asks about this concern by name.

## Parameters
Live in `memory/standing-concerns.md` under concern `{id}` (edit by talking to
Ernest, or `ernest disable-concern {id}` to switch off):
{params}

## Data sources (read-only; swappable)
1. VPS brain MCP when connected (search -> read -> write_watch_card).
2. Local MCP connectors.
3. `data/` exports (label items `source: local-export`).
Engine baseline: `ernest watch` (no model needed).

## Watch half
1. Read matching threads/contacts via the source order above.
2. Apply the `{playbook}` detection rules (see that skill for its thresholds).
3. Cross-check candidates in the other tools before flagging; suppress anything
   already handled elsewhere.
4. Write ONE remind-only card to `00-Watch/{id}--<date>.md`.

## Decision criteria
Refine after the first runs: what qualifies an item, how items rank, and the
tuning table (symptom -> which param/list to change). Until then the playbook
defaults apply.

## Draft half (explicit ask only)
On "draft these": ground in full threads (read-thread), voice from
`memory/ceo-persona.md`, write to `00-Drafts/` with STATUS: DRAFT. L2 — the CEO
approves before anything is sent.

## Output
Canonical reminder card — see `skills/ernest-watch/SKILL.md`. End summaries with
the standard reply line.

## Failure modes
- Source file/connector missing -> the engine writes no card at all (not an
  empty one); `ernest doctor` shows which source is down.

## Verification
Run `ernest watch` on sample or live data; confirm the card appears in
`00-Watch/` with the expected items. Then run the contract test.
"""


def scaffold(cfg: Config, concern_id: str, playbook: str, description: str,
             staleness: Optional[str] = None, intent: Optional[str] = None,
             window: Optional[str] = None) -> dict:
    if playbook not in _KNOWN_PLAYBOOKS:
        raise ValueError(
            f"Unknown playbook '{playbook}'. Known: {', '.join(sorted(_KNOWN_PLAYBOOKS))}"
        )
    params: dict[str, str] = {}
    if staleness:
        params["staleness"] = staleness
    if intent:
        params["intent"] = intent
    if window:
        params["window"] = window
    if playbook == "account-followup-recovery" and "staleness" not in params:
        params["staleness"] = "7d"
    if playbook == "inbox-prospect-followup" and "window" not in params:
        params["window"] = "90d"

    added = register(cfg, Concern(id=concern_id, playbook=playbook, enabled=True, params=params))

    skill_dir = cfg.skills_dir / concern_id
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_path = skill_dir / "SKILL.md"
    param_block = "\n".join(f"- {k}: {v}" for k, v in params.items()) or "- (none)"
    skill_path.write_text(
        _SKILL_TEMPLATE.format(
            id=concern_id,
            description=description or f"Automation for {concern_id}",
            title=concern_id.replace("-", " ").title(),
            playbook=playbook,
            params=param_block,
        ),
        encoding="utf-8",
    )
    return {"concern_added": added, "skill_path": skill_path, "params": params}
